### ISSUE TITLE
Issues to look into before PerDis demo

### ISSUE THREAD

**Issue by floe** [mmbuw/massive-mobile-multiplayer#4]
- [ ] Chrome on iOS doesn't work (known bug, but maybe we can find a workaround by now)
- [ ] Browsers in private mode don't seem to work (cookies?)
- [ ] iOS users in particular seem to get randomly disconnected

**Comment by floe** [comment]
* [ ] maybe get rid of the friction simulation for players?
* [ ] get rid of the very first landing page (!)

**Comment by floe** [comment]
* [ ] either reconnect the backend or disable the questionnaire at the end

**Comment by TimDomino** [comment]
The coefficient for the friction has been increased from 0.5 to 0.8 in c9cbd37, which makes the interaction feel more direct. The maximum coefficient of 1.0 however results in the player stopping when the direction is changed, which is an unwanted behaviour.
